/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_chaoyi_myapplication_AudioTrackPlay */

#ifndef _Included_com_chaoyi_myapplication_AudioTrackPlay
#define _Included_com_chaoyi_myapplication_AudioTrackPlay
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_chaoyi_myapplication_AudioTrackPlay
 * Method:    playSound
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_chaoyi_myapplication_AudioTrackPlay_playSound
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
